### ISSUE TITLE
If the property in the usercontrol is a Class type, in the saved XamlString, the property in the Class type attribute (Class type) will not be saved

### ISSUE THREAD

**Issue by NiMuQiao** [icsharpcode/WpfDesigner#104]
If the property in the usercontrol is a Class type, in the saved XamlString, the property in the Class type property (Class type) will not be saved。
![image](https://user-images.githubusercontent.com/76640283/221074950-f4af8467-f863-403a-816c-2283b4b9e2b7.png)
![image](https://user-images.githubusercontent.com/76640283/221074995-68d382ef-655b-4f30-9656-777c89c275d5.png)
![image](https://user-images.githubusercontent.com/76640283/221075264-cc996de7-965d-4fda-82a6-9b253f24616f.png)

**Comment by jogibear9988** [comment]
How do you set the Properties?

**Comment by NiMuQiao** [comment]
![image](https://user-images.githubusercontent.com/76640283/221145767-ce47b999-9299-42e1-aa13-610da653f4b9.png)
![image](https://user-images.githubusercontent.com/76640283/221146004-4dbcd592-2989-45c6-a39a-e62fffe2fc5d.png)
I just set the value in my PropertyEditor

**Comment by jogibear9988** [comment]
this will not work.
You need to set the Properties of the DesignItem

The DesignItem is an Wrapper wich encapsules every WPfControl. So for example also Bindings or Staticresources could be reflected in the Designer

**Comment by NiMuQiao** [comment]
Could you please provide me with an example, thank you very much

**Comment by jogibear9988** [comment]
Not really. Takes time and I don't know how you work with the designer in your code.
Maybe when you create a sample wich shows your error and upload it I could help.

**Comment by NiMuQiao** [comment]
Ok，thans so much！！！

**Comment by 237779932** [comment]
> Ok，thans so much！！！

Did you finally achieve your goal?

**Comment by 237779932** [comment]
`var property = PropertyNode.ValueItem.Parent.Properties.GetProperty("MyClass");
property.Value.Properties.GetProperty("PropertyName1")).SetValue(PropertyValue1);
property.Value.Properties.GetProperty("PropertyName2").SetValue(PropertyValue2);`

I added this code on top of your original one, and it works now.
