### ISSUE TITLE
can not build WpfDesigner

### ISSUE THREAD

**Issue by jagspaul** [icsharpcode/WpfDesigner#107]
getting error while build wpfdesigner

Error	MSB3644	The reference assemblies for .NETFramework,Version=v4.5 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks	WpfDesign.Designer.ExpressionBlendInteractionAddon	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets	1229

**Comment by DoLovya** [comment]
![image](https://github.com/icsharpcode/WpfDesigner/assets/73595300/562f68de-92c4-4541-b28b-690afb45ec1d)
