### ISSUE TITLE
Control Placed Outside the Window Disappears

### ISSUE THREAD

**Issue by RikaMi8** [icsharpcode/WpfDesigner#114]
When a control is placed outside the window and the focus moves to it, the control becomes completely invisible.  To select that control again, I need to choose it from the TreeView. 

https://github.com/user-attachments/assets/48638583-a9fd-4484-beac-1ec9ed3dfb19

Is there a way to display controls outside the window, similar to how the XAML designer in Visual Studio does?
![image](https://github.com/user-attachments/assets/23e6804a-99e2-4b00-ae50-96829284d2d3)

**Comment by jogibear9988** [comment]
If you set

     ClipToBounds="False"

here: https://github.com/icsharpcode/WpfDesigner/blob/38e9db5129bb1de297c23cc5860dba62b2b83ddd/WpfDesign.Designer/Project/Controls/ControlStyles.xaml#L196

it should work.

**Comment by jogibear9988** [comment]
You can copy the template for window clone to your code and override it

**Comment by RikaMi8** [comment]
@jogibear9988 
Thank you for your response. It's working well!
