### ISSUE TITLE
BorderForMouseOver of Line control is not displayed at correct position

### ISSUE THREAD

**Issue by YuuukiA** [icsharpcode/WpfDesigner#115]
For Line control, BorderForMouseOver is not displayed at correct position.
Would you please tell me how to fix it?

When I draw Line control from the top left to the bottom right, the border is displayed at correct position.
![image](https://github.com/user-attachments/assets/7fe030f5-86d6-40ff-b045-08d6bbe069a8)

When I draw Line control from the top right to the bottom left, the border is **not** displayed at correct position.
![image](https://github.com/user-attachments/assets/a1ef1cf6-7fb4-4da4-9fd3-ac8a27941a18)

**Comment by jogibear9988** [comment]
Could you create a pull req?
