### ISSUE TITLE
can't add same control

### ISSUE THREAD

**Issue by m4nd1cm4rk0** [icsharpcode/WpfDesigner#16]
I can't add same control twice. 
For example: 
when i add button, and i want to add another button, i can't. I must add some other control before add button again.

**Comment by m4nd1cm4rk0** [comment]
Possible solution is that use lstControls_PreviewMouseLeftButtonDown instead lstControls_SelectionChanged

**Comment by jogibear9988** [comment]
Where do you have that Problem? In the simple sample? This is only a small preview how to use the component! Look at the "XamlDesigner" example, there this works! There you can also add Controls via Drag Drop!

**Comment by jogibear9988** [comment]
Ok, I've fixed it with your changes! But please be next time more specific where you got the error... ;-)

**Comment by m4nd1cm4rk0** [comment]
Yes, in the simple sample. In some reason i can't open XamlDesigner example.

**Comment by jogibear9988** [comment]
Maybe report your error here as an issue

**Comment by m4nd1cm4rk0** [comment]
I managed to open XamlDesigner example. I look forward to solve new issues in your app :)
