### ISSUE TITLE
Width of the window when you run test isn't proportional

### ISSUE THREAD

**Issue by m4nd1cm4rk0** [icsharpcode/WpfDesigner#17]
When i'm created my window in XamlDesigner and go to Test->run, width of the window is bigger than in XamlDesigner.
For example:
default width is 640 and height is 480
when i run test first time width is bigger than 640, then i close the window
and change width to 641, and back to 640, and then i run again, and the window is ok.

**Comment by m4nd1cm4rk0** [comment]
this is when i run it for the first time
![first run](https://cloud.githubusercontent.com/assets/13752427/14409667/76f9387e-ff1a-11e5-92da-87fe1ccf0a87.png)

**Comment by m4nd1cm4rk0** [comment]
and this is when i run for second time, look at the width.
![second run](https://cloud.githubusercontent.com/assets/13752427/14409675/9235bafe-ff1a-11e5-82d2-3a3299295e29.png)

**Comment by m4nd1cm4rk0** [comment]
It seems that in the file NewFileTemplate.xaml should add default width and height of the window like this:
`<Window Width="640" Height="480" xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">
    <Canvas />
</Window>`

**Comment by jogibear9988** [comment]
I can change the template... (and will do), but the Projects that come with the designer, are only usage examples, not production apps!

**Comment by jogibear9988** [comment]
Fixed in https://github.com/icsharpcode/WpfDesigner/commit/6775dbfe9e39806d7ee200a68e67bb5a0cb5ac6b
