### ISSUE TITLE
Adding attached property breaks "Design" mode

### ISSUE THREAD

**Issue by javidang** [icsharpcode/WpfDesigner#22]
Hi. It is not critical issue, I find "hacky" solution for this, but it is curious why this happens. The problem is if I add attached property to something programmaticly or in "XAML" mode  (event trigger in my example), switching to "Design" mode not updates document, i mean it is still in "XAML" mode. I tried to find if generated window becomes null or some inner exception happens, but nothing, window is generated, and all functions act normal. Added example xaml as file.

[New1.txt](https://github.com/icsharpcode/WpfDesigner/files/262605/New1.txt)

**Comment by jogibear9988** [comment]
I'm on it! The Problem is that this Attached Properties use another Name for the Property as for the Field. I look how I solve this.

**Comment by javidang** [comment]
I currently tried to add that assemblies during loading settings. It know switches to design mode, but element that uses attached property not shown, and error tab complains about "attached property Interaction.Triggers not found" . It is more related to given example (System.Windows.Interactivity) I think. Google says it is Blend stuff, and it will work if you run it, but compiler will keep complaining. And if there is error, the element that element related will be dropped from design.

**Comment by jogibear9988** [comment]
As I said, WpfDesigner always looks for a Public Property ... Property, wich has a coresponding Get/Set Method! And this does not work there! I've started a fix, but I think I will not finish it before tuesday

**Comment by jogibear9988** [comment]
I've now got it working, but the Property is not yet displayed in the Property Grid! Problem is that it's a AttachedProperty, wich uses a Name for the Property wich is not the Same as the Static Object. Also the Static Object is Private, and if you call "TypeDescriptor.GetProperties(System.Windows:interactivity.Interaction)" you get no result!

**Comment by jogibear9988** [comment]
I'm not sure atm, how to solve this!

**Comment by jogibear9988** [comment]
Should now work, for the PropertyGrid, I'm still looking for a Solution
