### ISSUE TITLE
GradientSlider's GradientStop can not be repositioned.

### ISSUE THREAD

**Issue by openlisp** [icsharpcode/WpfDesigner#30]
The only working solution that has worked for me is following workaround in function thumb_DragDelta. . When dragged element is moved verticaly more than 50px It deleted. It allows to user insert new GradientStop to new position. 

 ````
        void thumb_DragDelta(object sender, DragDeltaEventArgs e)
        {
            var stop = (e.OriginalSource as GradientThumb).GradientStop;
            if (e.VerticalChange > 50 && GradientStops.Count > 2)
            {
                GradientStops.Remove(stop);
            }
        }
````

![image](https://user-images.githubusercontent.com/3258253/28035830-54613ee8-65b6-11e7-94f6-36d07b253389.png)

**Comment by jogibear9988** [comment]
The DragDrop of the Thumb is canceled by Wpf, I don't know why atm... Don't know if a assignment of a Thumbs offset stops a active DragDrop.

**Comment by awraae** [comment]
I have a fix for this in a local branch. I can make a pull request when I am back from vacation next week.

**Comment by jogibear9988** [comment]
cool :-)
would be nice!
thx
