### ISSUE TITLE
Element constant rotation

### ISSUE THREAD

**Issue by mnusr** [icsharpcode/WpfDesigner#35]
If you select an element and click on the rotation handle and move your mouse to the right, the element starts rotate constantly and fast.
Is that a normal behavior? can that be stopped or adjusted?

**Comment by jogibear9988** [comment]
this is broken atm... i'm looking to fix if i find time...

**Comment by jogibear9988** [comment]
i'd like how the rotation, resize and skew work in https://transformbox.codeplex.com
i'd look what i can take of this project

**Comment by jogibear9988** [comment]
I've not yet switched the Transformation Extensions, but the Rotation should work now...
