### ISSUE TITLE
Change Resizing, Skewing & Rotateing of Controls

### ISSUE THREAD

**Issue by jogibear9988** [icsharpcode/WpfDesigner#37]
It should worke like https://github.com/jogibear9988/transformbox

**Comment by JoshWobbles** [comment]
Would this address unwanted changes to horizontal and vertical alignment when moving elements around?

**Comment by jogibear9988** [comment]
don‘t know. 
don‘t think I will get to this task the next time.

the alignment is modified when you change to a new container, depending on the position (near to wich side or the middle)

**Comment by JoshWobbles** [comment]
Ive had it change when not even changing containers (not pressing the modifier key) and it seems much more easy for it to attach to the bottom or right than I notice when using Visual Studio. I am used to VS behaving more like defaulting to top left unless within like 10px or so.

Is there a way to override this behavior or make it alwayse default to top left?
