### ISSUE TITLE
Designer not updating

### ISSUE THREAD

**Issue by mnusr** [icsharpcode/WpfDesigner#38]
Context:
The design surface and the xaml editor are both in the same grid split by a splitter.
When xaml changes TextChanged fires and loads the designer using LoadDesigner method.
However nothing seems to be happening, the designer only updates when I click anywhere in the designer.
What can I do force the designer to update when the xaml changes?
Thanks.

**Comment by jogibear9988** [comment]
can you create a sample project? or maybe change the simplesample and create a pull request, then maybe i can look

**Comment by mnusr** [comment]
I just realized, it was passing blank xaml, dispatching the call took care of it.
My apologies.
