### ISSUE TITLE
Changed event

### ISSUE THREAD

**Issue by mnusr** [icsharpcode/WpfDesigner#39]
Does the designer have any event that will fire when any change is made to the designer?
I simply want to update my text/code editor as soon as the anything in the designer changes.
I've looked and haven't found anything so far.

**Comment by awraae** [comment]
Hi mnusr. I use the UndoService.UndoStackChanged event for the same purpose.

SomeDesignItem.Services.GetService<UndoService>().UndoStackChanged += ...

**Comment by mnusr** [comment]
Thanks @awraae, I would've thought there would've been a generic event for this purpose, I guess this will have to do just now.

**Comment by awraae** [comment]
Anytime @mnusr. I had the same feeling at first. But when you think about it: every change to the DesignItem model is executed through the UndoService. So I actually think that this is the “generic event" you are looking for.
