### ISSUE TITLE
System IO Exception

### ISSUE THREAD

**Issue by codirx** [icsharpcode/WpfDesigner#43]
![ads](https://user-images.githubusercontent.com/40802899/42413278-e3b4b458-8225-11e8-9227-d4c97a5fd0d7.png)
When I adding a control program gives me that error. Please help me

**Comment by jogibear9988** [comment]
I could not reproduce this.

Can you create small sample showing the problem? Which Framework Version do you use?

**Comment by codirx** [comment]
![sda](https://user-images.githubusercontent.com/40802899/42449784-a1a03b12-838a-11e8-871e-b3c5e63ffff4.png)

**Comment by jogibear9988** [comment]
No, it's default that the 3.0 DLL is loaded

**Comment by jogibear9988** [comment]
what is the %c4%b1 in the xaml file name?

**Comment by kivannc** [comment]
I had the same problem. It is related to CultureInfo when the function below is called ToLower() function creates the wrong file name.  I have added the 'CultureInfo.InvariantCulture' and its fixed.

`public static string GetXamlNameForType(Type t)
{
	return _uriStart + t.FullName.Substring(_subLength).Replace(".","/").ToLower() + ".xaml";
}`

`public static string GetXamlNameForType(Type t)
{
	return _uriStart + t.FullName.Substring(_subLength).Replace(".","/").ToLower(CultureInfo.InvariantCulture) + ".xaml";
}`

Before fileName was "wrap**ı**temcontextmenu.xaml" and after changing it was correct "wrapitemcontextmenu.xaml"
