### ISSUE TITLE
New feature needed: Specifying Properties

### ISSUE THREAD

**Issue by closetao** [icsharpcode/WpfDesigner#45]
Hi
First of all, thank you for the project you provided.
I create a new usercontrol and I want to hide all inherit properties in PropertyGrid. `Browsable` is one option, but it is not convenient for hiding all inherit properties. Referring the similar project `wpftoolkit`, its PropertyGrid can hide all properties by using `AutoGenerateProperties`  at one time. Can you add this feature? 

Wating for your reply. 
Thanks

source code reference: [ObjectContainerHelper.cs](https://github.com/xceedsoftware/wpftoolkit/blob/24ecc09cf35e7095ad02d0beecfd5bafd83d0658/ExtendedWPFToolkitSolution/Src/Xceed.Wpf.Toolkit/PropertyGrid/Implementation/ObjectContainerHelper.cs#L90)

[usage description](https://github.com/xceedsoftware/wpftoolkit/wiki/PropertyGrid)

**Comment by jogibear9988** [comment]
This is already possible, Look at MyTestAssembly -> MyComponentPropertyService
