### ISSUE TITLE
Custom Right Click Item on DesignItem 

### ISSUE THREAD

**Issue by haftado3** [icsharpcode/WpfDesigner#47]
could you help me add my own Item to DesignItem Right click menu? with event handlers for that?

**Comment by jogibear9988** [comment]
look at RightClickContextMenuExtension
if you do a extension like this, it will be added to the right click menu

you need to add your assembly to the designer assemblies:

            var settings = new XamlLoadSettings();
            settings.DesignerAssemblies.Add(blabla);
