### ISSUE TITLE
Selection Handling on Design Surface

### ISSUE THREAD

**Issue by haftado3** [icsharpcode/WpfDesigner#48]
i'm using this code to change SelectionChanged handler on DesignSurface 
```
 designSurface.DesignContext.Services.Selection.SelectionChanged += delegate
            {
                   var selection = designSurface.DesignContext.Services.Selection.SelectedItems.First().Component ;
                   CommandManager.InvalidateRequerySuggested();
            };
```
i feel like its wrong what is the correct way to do this in DesignSurface ?
i need to get data from Selected Item but its not DesignItem , i've Added My own Control to it

**Comment by jogibear9988** [comment]
Again, I don‘t understand the question!
But you could use PrimarySelection instead of SelectedItems

**Comment by haftado3** [comment]
i have items on design surface 
i could select them so 
i need to add event to when onSelectionChanged
what is right way to do that?

**Comment by jogibear9988** [comment]
whats wrong with

       designSurface.DesignContext.Services.Selection.SelectionChanged

**Comment by haftado3** [comment]
sorry my fault this one is totally working
