### ISSUE TITLE
DesignPanel Unwanted Enlargement

### ISSUE THREAD

**Issue by haftado3** [icsharpcode/WpfDesigner#50]
moving DesignItem to top-left Corner of DesignSurface will make DesignPanel Bigger that is so Annoying . could we completely disable it?

**Comment by jogibear9988** [comment]
Again, don't understand your issue

**Comment by haftado3** [comment]
we have a design area,
we can add DesignItem to DesignSurface
you can change DesignItems position by drag and dropping 
but dragging these to edge of screen making scroll View of DesignPanel Get bigger 
i want to disable it ,these scroll view cant resize itself when you drag and drop components

**Comment by jogibear9988** [comment]
Look at my Example App "MyDesigner" in the Source. If you set Width and Height of the Grid in the Template (Line 23 in MainWindow.xaml.cs)

     x:Name=""rootElement"" Background=""White"" Width=""200"" Height=""200""><Grid  Margin=""100""/></Grid>";

it will not scroll

**Comment by haftado3** [comment]
ty it did work
