### ISSUE TITLE
Enhancement: Make FontFamily a combo box instead of text field in property editor

### ISSUE THREAD

**Issue by JoshWobbles** [icsharpcode/WpfDesigner#59]
Would be nice to "select" a font rather than looking up it's name and having to type it in.

**Comment by jogibear9988** [comment]
It is a combobox in the Demo.XamlDesigner sample

**Comment by JoshWobbles** [comment]
How? The sample I base off of "SimpleSample", its a text field, no combo box.

**Comment by jogibear9988** [comment]
You need to add 
BasicMetadata.Register();
was missing in Simple Sample

**Comment by JoshWobbles** [comment]
You're on a roll today!
