### ISSUE TITLE
Way to render custom UserControl

### ISSUE THREAD

**Issue by Thaval** [icsharpcode/WpfDesigner#68]
Hi,

is there a way to render custom UserControls?
I experience the problem that there won't be thrown an exception when wrapping for example a "Grid" within a "UserControl" but it's not displayed in the designer. Whenever I remove the UserControl, so the Grid is the root element, then the grid and it's button content will be rendered/displayed.

**Comment by jogibear9988** [comment]
What is you root Element in xaml? UserControl class or a special UserControl class you created. If so, is the DLL defining this class also referenced?

**Comment by Thaval** [comment]
Got it working after hours of researching. The problems I had existed because I thought the XamlReader can handle a default WPF Xaml, but it can't.

My root element is "UserControl". I read some articles and removed the x:Class respectively as it seems that the XamlReader does only support loose xaml (always the typical Microsoft half-way solutions...).
However, before passing the Xaml to the DesignerSurface, I manipulate the Xaml:

- Get the inner node of the UserControl (if I get ressource like UserControl.Ressources, this method will fail) and handle it as new root element
- Copy all attributes from the UserControl to the new root element
- Find all clr-namespaces and add the assemblies to the types like (clr-namespace:MyNamespace.Control;assembly=ExampleProject")

Seems fine for now. I'm pretty sure I will need to adjust a lot of stuff, but currently I'm fighting with AvalonEdit.
