### ISSUE TITLE
A Bug in 5c19b18 Commited on Sep 13, 2021

### ISSUE THREAD

**Issue by ZJun96** [icsharpcode/WpfDesigner#78]
When I select a control, such as Button, keep dragging this control, and moving around on design window, Demo.XamlDesigner program report a assert error in UndoService.cs: line 101.
Probably reason is the correction in CreateComponentTool.cs: line 194 on lasted version. 
I suggest deleting CreateComponentTool.cs: line 194 as the older version.

**Comment by jogibear9988** [comment]
fixed it, thanks for the info
