### ISSUE TITLE
How do i add controls to my design surface programmatically?

### ISSUE THREAD

**Issue by Jerry2306** [icsharpcode/WpfDesigner#89]
I want to add UserControls to my design surface programmatically.
First i tried adding it to the children UIElementCollection for my root control (which is a grid). When i've done this i couldn't select the control on the surface, but it appeared.
Then i tried it via the CreateComponentTool. With this i can select the control on the surface and move it. But the control is positioned outside my design panel (i think the design panel is the root document, were i can order my controls on and the design surface is the whole design control, containing the design panel?):
![image](https://user-images.githubusercontent.com/58561143/181442619-b6f1fb66-e200-4b02-b8fe-e2621f043315.png)

As well the control must have VerticalAlignment->Bottom and HorizontalAlignment->Right. But i want it to be from Top, Left:
![image](https://user-images.githubusercontent.com/58561143/181443335-5248ccbd-2b97-4784-88fd-2febfa4672a0.png)

I made the AddItemsWithDefaultSize method (in CreateCompnentTool) public so i can create my DesignItem and can pass it directly down, instead of letting the CreateComponentTool do this (i want to manipulate attributes of my obj). I have tried it as follows:
![image](https://user-images.githubusercontent.com/58561143/181444504-4e5e14c4-bbb5-4624-9576-8f8b96164a16.png)

My UserControl should not be the problem as it is added right via the toolbox.

Thanks in advance and best regards
Jeremy

**Comment by jogibear9988** [comment]
I create the instance of the item I'd like to add. Register it as designItem via .RooItem.Services.Component.Register...
And then I add this DesignItem to the root Item

**Comment by Jerry2306** [comment]
@jogibear9988 Thank you very much! If I'm creating my DesignItem via the "RegisterComponentForDesigner" method instead of the "CreateComponentTool.CreateItem" it works like a charm.

For whoever is interested how i solved it:
![grafik](https://user-images.githubusercontent.com/58561143/186510066-2bc0d502-76ce-4d8e-a1d8-5bde5bf9e8d8.png)
