### ISSUE TITLE
I found 3 issues

### ISSUE THREAD

**Issue by BillShawn** [icsharpcode/WpfDesigner#90]
1,DataGrid can not edit colunms with its right top contextmenu
2,ever control outside tabcontrol can not drag to tabcontrol's tabitem,it will create a new sub item but type is not TabItem
3,ever control drag in DataGrid 

issue 1 :QuickOperationMenuExtension.cs  line 71 
how to resolve issue 1 and issue  2?

**Comment by BillShawn** [comment]
well, issue 3 is closed now;

**Comment by BillShawn** [comment]
a new issue, ComboBoxEditor can not work. change ComboBoxEditor.xaml content
`<ComboBox
	x:Class="ICSharpCode.WpfDesign.Designer.PropertyGrid.Editors.ComboBoxEditor"
	xmlns="http://schemas.microsoft.com/netfx/2007/xaml/presentation"
	xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
	xmlns:local="clr-namespace:ICSharpCode.WpfDesign.Designer.Controls"
	BorderThickness="1"
	SelectedValue="{Binding DesignerValue}"
	Background="Transparent"
	Focusable="False"
	Margin="0"
	VirtualizingStackPanel.ScrollUnit="Pixel" 
	VirtualizingStackPanel.IsVirtualizing="True" 
	ScrollViewer.CanContentScroll="True"
>

</ComboBox>`
now ,it work

**Comment by jogibear9988** [comment]
Could you create pull requests with fixes for your issues?
I've no time to look for the at the moment

**Comment by BillShawn** [comment]
Iuess 2 and 3,cancel drag control to TabControl and DataGrid
Line15 -Line154,source code is :
`
if (ExtendedItem.ContentProperty.IsCollection)
				return CollectionSupport.CanCollectionAdd(ExtendedItem.ContentProperty.ReturnType,
														  operation.PlacedItems.Select(p => p.Item.Component));
`
change it 
`

if (ExtendedItem.ContentProperty.IsCollection)
			{
				if (ExtendedItem.Component is Panel)
					return CollectionSupport.CanCollectionAdd(ExtendedItem.ContentProperty.ReturnType,
															  operation.PlacedItems.Select(p => p.Item.Component));
				return false;
			}

`
