### ISSUE TITLE
Hello how do I use this I installed this via nuget now how do I use ?

### ISSUE THREAD

**Issue by SunnyPotatos** [icsharpcode/WpfDesigner#99]
Hello, how do I use this, I installed this via nuget, now how do I use C# to call wpf form to draw the interface

**Comment by jogibear9988** [comment]
there is a sample using the nugets in the repo

**Comment by jogibear9988** [comment]
simplesample

**Comment by SunnyPotatos** [comment]
When I modified UserControl after Wpf MainWindow, I instantiated and invoked it in two panels of Winform respectively. Why did they affect each other? Thank you
